### ISSUE TITLE
Even if `ignore` is configured, it will still be repaired

### ISSUE THREAD

**Issue by A-kirami** [charliermarsh/ruff-vscode#165]
Ignore the F401 rule like this.

```toml
[tool.ruff]
ignore = ["F401"]
```

But it will automatically repair when you save the file.

When I use `ruff` on the command line, there is no such problem.
