### ISSUE TITLE
Stops working if config file is named .ruff.toml or ruff.toml

### ISSUE THREAD

**Issue by CHerSun** [charliermarsh/ruff-vscode#167]
Hi.

I've been playing with a configuration for vscode ruff today. If I name the config file as `pyproject.toml` - it works perfectly fine, shows problems on problems tab, highlights them in code.

But if I place the same config into `.ruff.toml` or `ruff.toml` - the addon stops working completely - no highlights, no problems listed. I might be doing something wrong, it's my first time trying to build my config for ruff.

**Comment by charliermarsh** [comment]
If you migrate from `pyproject.toml` to `ruff.toml`, be sure to remove the `[tool.ruff]` prefix from any content.

For example, if your `pyproject.toml` is:

```toml
[tool.ruff]
select = ["B"]

[tool.ruff.pydocstyle]
convention = "google"
```

Then your `ruff.toml` should be:

```toml
select = ["B"]

[pydocstyle]
convention = "google"
```

This is just a guess, may be some other issue, but the above is why a straight rename of the file could stop Ruff from working properly.
